### ISSUE TITLE
Mobile/responsive design

### ISSUE THREAD

**Issue by charlielafosse** [FAC-Sixteen/sparks-todo#12]
Your app actually scales down really nicely into mobile:

![](http://i.imgur.com/yl8FX20.png)

There may be slight adjustments you'd want to make in the todos/`li` elements, but overall it functions as it should and looks great.

**Comment by dubhcait** [comment]
Eat a yoga mat? 

![](https://media.giphy.com/media/51Uiuy5QBZNkoF3b2Z/giphy.gif)

**Comment by aniablaziak** [comment]
<img width="400" alt="Screenshot 2019-03-15 at 12 06 20" src="https://user-images.githubusercontent.com/39386043/54430229-d896e400-471a-11e9-82ad-482746195eef.png">
Fixed! It also breaks long words now 🙃

**Comment by charlielafosse** [comment]
WOoo!
