### ISSUE TITLE
addTodo function

### ISSUE THREAD

**Issue by charlielafosse** [FAC-Sixteen/sparks-todo#14]
in your `logic.js` file, `line 26`

First off, great job on writing this really cleanly and getting it working! And nice use of ES6.

Just be careful with your naming conventions: 

```

let clonedArray = {
            id: todoFunctions.generateId(),
            description: newTodo,
            done: false
        };

```

This threw me off a little bit, just as this object variable you've created isn't the cloned array - it's the todo object that you're constructing, that you will then pass into the cloned array (which is `todoFunctions.cloneArrayOfObjects(todos)`).

A small point!

**Comment by dubhcait** [comment]
Thanks so much, I meant to change it as it was a brain dead first day frustrations, newObject is much more accurate
