### ISSUE TITLE
Requiring exported objects

### ISSUE THREAD

**Issue by charlielafosse** [FAC-Sixteen/sparks-todo#20]
A small slip up in one of your tests, `line 80`:

`let actual = logic.todoFunctions.generateId;`

Remember that what you've exported from your `logic.js` file is the `todoFunctions` object - **but**, what you've required it as in your `test.js` file is the `logic` variable (which means that the 'todoFunctions' variable name kinds of becomes defunct).

Although, you've done this in other tests, so I guess this was just a slip of the mind.

**Comment by dubhcait** [comment]
thanks that was a remnant from the merge conflict aswell
